python/20190308/flask_qa_app/app/main/views.py
from flask import Blueprint, request, jsonify, flash, redirect, url_for, render_template, current_app
from flask_login import current_user

from app.utils import fetch_question
from app.models import Question, Answer, Comment

qa_bp = Blueprint('qa', __name__, url_prefix='')


@qa_bp.route('/')
def index():
    link, info = fetch_question(current_app.config['QUESTION_URL'])
    return render_template('index.html', link=link, info=info)


@qa_bp.route('/question/add')
def add_question():
    return render_template('ask_question.html')


@qa_bp.route('/question', methods=['GET', 'POST'])
def question_info():
    try:
        _form = request.form
        if request.method == 'POST':
            if not current_user.is_authenticated:
                return jsonify(status='error', info='请先登录')
            Question(
                name=_form.get('title'),
                content=_form.get('content'),
                author_id=current_user.id
            ).save()
            return jsonify(status='success', info='发布成功')
        else:
            question_list = Question.query.filter().all()
            return render_template('questions.html', qss=question_list)

    except Exception as e:
        print(e)
        raise


@qa_bp.route('/questions/<int:question_id>')
def questions(question_id):
    question_instance = Question.query.filter(Question.id == question_id).first_or_404()
    print(dir(question_instance))
    if question_instance:
        return render_template('question_detail.html', qs=question_instance)
    return redirect(url_for('qa.index'))


@qa_bp.route('/question/<int:question_id>/answer', methods=['POST'])
def add_reply(question_id):
    _form = request.form
    if not current_user.is_authenticated:
        return jsonify(status='error', info='请先登录')
    question_instance = Question.query.filter(Question.id == question_id).first_or_404()
    if _form.get('rtype') == '1':
        # 回答
        Answer(
            content=_form.get('content'),
            author_id=current_user.id,
            question_id=question_id
        ).save()
        question_instance.answers_count += 1
        question_instance.save()
        return jsonify(status='success', info='回复成功')
    elif _form.get('rtype') == '2':
        answer_instance = Answer.query.filter(Answer.id==_form.get('rid')).first_or_404()
        # 评论
        Comment(
            content=_form.get('content'),
            author_id=current_user.id,
            answer_id=answer_instance.id
        ).save()
        answer_instance.comments_count += 1
        answer_instance.save()
        return jsonify(status='success', info='评论成功')

python/20190308/flask_qa_app/app/templates/ask_question.html
{% extends "base.html"%}
{% block content %}
<div class="breadcrumbs">
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>提问</h1>
            </div>
        </div><!-- End row -->
    </section><!-- End container -->
</div><!-- End breadcrumbs -->


<section class="container main-content">
    <div class="row">
        <div class="col-md-9">
            <div class="page-content ask-question">
                <div class="boxedtitle page-title"><h2>提问</h2></div>
                <div class="form-style form-style-3" id="question-submit">
                    <form>
                        <div class="form-inputs clearfix">
                            <p>
                                <label class="required">问题标题<span>*</span></label>
                                <input type="text" id="question-title">
                                <span class="form-description">标题</span>
                            </p>
                        </div>
                        <div id="form-textarea">
                            <p>
                                <label class="required">问题详细<span>*</span></label>
                                <textarea id="question-details" aria-required="true" cols="58" rows="8"></textarea>
                                <span class="form-description">问题的详细描述</span>
                            </p>
                        </div>
                        <p class="form-submit">
                            <input type="button" id="publish-question" value="提交问题" class="button color small submit">
                        </p>
                    </form>
                </div>
            </div>
        </div>
        {% if current_user.is_authenticated %}
        <aside class="col-md-3 sidebar">
            <div class="widget">
                    <h3 class="widget_title">用户名：{{ current_user.username }}</h3>
                    <a href="{{url_for("auth.logout")}}">
                        <input type="button" value="退出登录" class="button color small">
                    </a>
            </div>
        </aside>
        {% endif %}
    </div>
</section>
<div id="question-data" url="{{ url_for('qa.question_info') }}"></div>
{% endblock %}

{% block footer %}
<script src="/static/js/ask.js"></script>
{% endblock %}

python/20190308/flask_qa_app/app/templates/base.html
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="UTF-8">
    <title>QA</title>
    <meta name="author" content="liusong">

    <!-- 移动 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Main Style -->
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- Skins -->
    <link rel="stylesheet" href="/static/css/skins/blue.css">
    <!-- Responsive Style -->
    <link rel="stylesheet" href="/static/css/responsive.css">
    <!-- Favicons -->
    <link rel="shortcut icon" href="/static/images/favicon.ico">

</head>
<body>
<div class="loader"><div class="loader_html"></div></div>

<div id="wrap" class="grid_1200">

    {% if not current_user.is_authenticated %}
    <div class="login-panel">
        <section class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="page-content">
                        <h2>登陆</h2>
                        <div class="form-style form-style-3">
                            <form method="post" action="{{url_for('auth.login')}}">
                                <div class="form-inputs clearfix">
                                    <p class="login-text">
                                        <input type="text" name="username" value="Username or Email" onfocus="if (this.value == 'Username or Email') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Username or Email';}">
                                        <i class="icon-user"></i>
                                    </p>
                                    <p class="login-password">
                                        <input type="password" name="password" value="">
                                        <i class="icon-lock"></i>
                                        <!-- <a href="#">Forget</a> -->
                                    </p>
                                </div>
                                <p class="form-submit login-submit">
                                    <input type="submit" value="登陆" class="button color small login-submit submit">
                                </p>
                                <!--
                                <div class="rememberme">
                                    <label><input type="checkbox" checked="checked"> Remember Me</label>
                                </div> -->
                            </form>
                        </div>
                    </div><!-- End page-content -->
                </div><!-- End col-md-6 -->
                <div class="col-md-6">
                    <div class="page-content Register">
                        <h2>注册</h2>
                        <p></p>
                        <a class="button color small signup">注册</a>
                    </div><!-- End page-content -->
                </div><!-- End col-md-6 -->
            </div>
        </section>
    </div><!-- End login-panel -->
    {% endif %}


    {% if not current_user.is_authenticated %}
    <div id="header-top">
        <section class="container clearfix">
            <nav class="header-top-nav">
                <ul>
                    <li><a href="login.html" id="login-panel"><i class="icon-user"></i>登陆</a></li>
                </ul>
            </nav>
            <!-- <div class="header-search">
                <form>
                    <input type="text" value="Search here ..." onfocus="if(this.value=='Search here ...')this.value='';" onblur="if(this.value=='')this.value='Search here ...';">
                    <button type="submit" class="search-submit"></button>
                </form>
            </div>-->
        </section><!-- End container -->
    </div><!-- End header-top -->
    {% endif %}
    <header id="header">
        <section class="container clearfix">
            <div class="logo"><a href="{{ url_for('qa.index') }}"><img alt="" src="/static/images/logo.png"></a></div>
            <nav class="navigation">
                <ul>
                    <li id="nav-index"><a href="{{ url_for('qa.index') }}">首页</a>
                    {% if current_user.is_authenticated %}
                        <li id="nav-username"><a href="#">{{ current_user.username }}</a></li>
                        <li id="nav-logout"><a href="{{ url_for('auth.logout')}}">退出</a></li>
                    {% endif %}
                        <!-- <ul>
                            <li class="current_page_item"><a href="index.html"></a></li>
                        </ul> -->
                    </li>
                    <li id="nav-ask"><a href="{{ url_for('qa.add_question') }}">提问</a></li>
                    <li id="nav-question"><a href="{{ url_for('qa.question_info') }}">问题</a></li>
                </ul>
            </nav>
        </section><!-- End container -->
    </header><!-- End header -->
    {% block content %} {% endblock %}


{% if not current_user.is_authenticated %}
<div class="panel-pop" id="signup">
    <h2>注册<i class="icon-remove"></i></h2>
    <div class="form-style form-style-3">
        <form>
            <div class="form-inputs clearfix">
                <p>
                    <label class="required">用户名<span>*</span></label>
                    <input type="text" name="name" id="name">
                </p>
                <p>
                    <label class="required">邮箱<span>*</span></label>
                    <input type="email" name="email" id="email">
                </p>
                <p>
                    <label class="required">密码<span>*</span></label>
                    <input type="password" name="password" value="" id="password">
                </p>
                <p>
                    <label class="required">确认密码<span>*</span></label>
                    <input type="password" name="confirm_password" value="" id="confirm_password">
                </p>
            </div>
            <p class="form-submit">
                <input type="button" value="注册" class="button color small submit" id="submit-button">
            </p>
        </form>
    </div>
</div><!-- End signup -->
<div id="signup-data" url="{{ url_for('auth.register')}}"></div>
{% endif %}

<!-- js -->
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="/static/js/jquery.easing.1.3.min.js"></script>
<script src="/static/js/html5.js"></script>
<script src="/static/js/twitter/jquery.tweet.js"></script>
<script src="/static/js/jflickrfeed.min.js"></script>
<script src="/static/js/jquery.inview.min.js"></script>
<script src="/static/js/jquery.tipsy.js"></script>
<script src="/static/js/tabs.js"></script>
<script src="/static/js/jquery.flexslider.js"></script>
<script src="/static/js/jquery.prettyPhoto.js"></script>
<script src="/static/js/jquery.carouFredSel-6.2.1-packed.js"></script>
<script src="/static/js/jquery.scrollTo.js"></script>
<script src="/static/js/jquery.nav.js"></script>
<script src="/static/js/tags.js"></script>
<script src="/static/js/jquery.bxslider.min.js"></script>
<script src="/static/js/custom.js"></script>

{% block footer %}
{% endblock %}
<!-- End js -->

</body>
</html>

python/20190308/flask_qa_app/app/templates/index.html
{% extends "base.html"%}
{% block content %}
{#    {% if current_user.is_authenticated %}#}
{#    <section class="container main-content">#}
{#        <div class="row">#}
{#            <div class="col-md-9">#}
{#            </div>#}
{#            <aside class="col-md-3 sidebar">#}
{#                <div class="widget">#}
{#                        <h3 class="widget_title">用户名：{{ current_user.username }}</h3>#}
{#                        <a href="{{url_for("auth.logout")}}">#}
{#                            <input type="button" value="退出登录" class="button color small">#}
{#                        </a>#}
{#                </div>#}
{#            </aside>#}
{#        </div>#}
{#    </section>#}
{#    {% endif %}#}
    <div class="section-warp ask-me">
        <div class="container clearfix">
            <div class="box_icon box_warp box_no_border box_no_background" box_border="transparent" box_background="transparent" box_color="#FFF">
                <div class="row">
                    <div class="col-md-3">
                        <h2>知否热门话题</h2>
                        <a href="{{ link }}">{{ info }}</a>
                        <div class="clearfix"></div>
                        <br>
                        <br>
                        <a class="color button dark_button medium" href="#">关于我们</a>
                        <a class="color button dark_button medium" href="#">加入</a>
                    </div>
                    <div class="col-md-9">
                        <dl>
                            {% for category, msg in get_flashed_messages(with_categories=true) %}
                            {% if category=='error' %}
{#                               <strong><dd style="color: red">{{ msg }}</dd> </strong>#}
                                <script>
                                alert('错误: {{ msg }}')
                                </script>
                            {% else %}
                                <script>
                                alert('提示: {{ msg }}')
                                </script>
                            {% endif %}
                            {% endfor %}
                        </dl>
                        <form class="form-style form-style-2">
                            <p>
                                <textarea rows="4" id="question_title" onfocus="if(this.value=='')this.value='!!!';" onblur="if(this.value=='')this.value='!!!';">!!!</textarea>
                                <i class="icon-pencil"></i>
                                <span class="color button small publish-question">提交问题</span>
                            </p>
                        </form>
                    </div>
                </div><!-- End row -->
            </div><!-- End box_icon -->
        </div><!-- End container -->
    </div><!-- End section-warp -->
</div>

{% endblock %}

{% block footer %}
<script src="static/js/index.js"></script>
<script src="static/js/check.js"></script>
{% endblock %}

python/20190308/flask_qa_app/app/templates/question_detail.html
{% extends "base.html"%}
{% block content%}
<div class="breadcrumbs">
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{qs.name}}</h1>
            </div>
            <div class="col-md-12">
                <div class="crumbs">
                    <a href="#">问题</a>
                    <span class="crumbs-span">/</span>
                    <span class="current">{{qs.name}}</span>
                </div>
            </div>
        </div><!-- End row -->
    </section><!-- End container -->
</div><!-- End breadcrumbs -->

<section class="container main-content">
    <div class="row">
        <div class="col-md-9">
            <article class="question single-question question-type-normal">
                <h2>{{ qs.name }}</h2>
                <div class="question-type-main"><i class="icon-question-sign"></i>问题</div>
                <div class="question-inner">
                    {{ qs.content }}
                </div>
            </article>
            <div class="about-author clearfix">
                    <!-- <div class="author-image"> -->
                        <!-- <a href="#" original-title="admin" class="tooltip-n"><img alt="" src="http://placehold.it/60x60/FFF/444"></a> -->
                    <!-- </div> -->
                <div class="author-bio">
                    <h4>作者:</h4>
                    <p>{{ qs.author.username }}</p>
                </div><!-- End about-author -->
            </div>
            <div id="commentlist" class="page-content">
                <div class="boxedtitle page-title"><h2>答案 ( <span class="color">{{qs.answers_count}}</span> )</h2></div>
                <ol class="commentlist clearfix">
                    {% for ans in qs.answers%}
                         <li class="comment">
                               <div class="comment-body comment-body-answered clearfix">
                                    <div class="avatar"><img alt="" src="https://oss.love2.io/759e0408-e78c-11e7-872e-00163e0f8adb.png?x-oss-process=style/300x300"></div>
                                    <div class="comment-text">
                                        <div class="author clearfix">
                                            <div class="comment-author"><a href="#">{{ ans.author.name }}</a></div>
                                            <div class="comment-meta">
                                                <div class="date"><i class="icon-time"></i> {{ans.create_time}}</div>
                                            </div>
                                            <a class="comment-reply" href="#respond" ans-id="{{ ans.id }}" id="reply-answer"><i class="icon-reply"></i>回复</a>
                                        </div>
                                        <div class="text">
                                            <p> {{ ans.content }}</p>
                                        </div>
                                    </div>
                               </div>
                               <ul class="children">
                                   {% for cm in ans.comments%}
                                   评论:
                                    <li class="comment">
                                        <div class="comment-body comment-body-answered clearfix">
                                            <div class="avatar"><img alt="" src="https://oss.love2.io/bbab4c64-db5f-11e7-872e-00163e0f8adb.png?x-oss-process=style/300x300"></div>
                                            <div class="comment-text">
                                                <div class="author clearfix">
                                                    <div class="comment-author"><a href="#">{{ cm.author.name }}</a></div>
                                                    <div class="comment-meta">
                                                        <div class="date"><i class="icon-time"></i> {{cm.create_time}}</div>
                                                    </div>
                                                </div>
                                                <div class="text">
                                                    <p> {{ cm.content }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    {% endfor %}
                               </ul>
                         </li>
                    {% endfor %}
                </ol>
            </div>
            <div id="respond" class="comment-respond page-content clearfix">
                <div class="boxedtitle page-title"><h2>提交回复</h2></div>
                <div id="reply-info" rtype="1" rid="" qs-url="{{ url_for('qa.add_reply', question_id=qs.id) }}"></div>
                    <form action="" method="post" id="commentform" class="comment-form">
                        <div id="respond-textarea">
                            <p>
                                <label class="required" for="comment">回复<span>*</span></label>
                                <textarea id="comment" name="comment" aria-required="true" cols="58" rows="8"></textarea>
                            </p>
                        </div>
                        <p class="form-submit">
                            <input name="submit" type="button" id="submit" value="提交" class="button small color">
                        </p>
                    </form>
                </div>
            </div>
        {% if current_user.is_authenticated %}
        <aside class="col-md-3 sidebar">
            <div class="widget">
                    <h3 class="widget_title">用户名：{{ current_user.username }}</h3>
                    <a href="{{url_for("auth.logout")}}">
                        <input type="button" value="退出登录" class="button color small">
                    </a>
            </div>
        </aside>
        {% endif %}
    </div>
</section>
{% endblock %}

{% block footer %}
<script src="/static/js/questions.js"></script>
{% endblock %}

python/20190308/flask_qa_app/app/templates/questions.html
{% extends "base.html"%}
{% block content%}
<div class="breadcrumbs">
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>问题列表</h1>
            </div>
            <div class="col-md-12">
                <div class="crumbs">
                        <span class="current">问题列表</span>
                </div>
            </div>
        </div><!-- End row -->
    </section><!-- End container -->
</div><!-- End breadcrumbs -->

<section class="container main-content">
    <div class="row">
        <div class="col-md-9">
            {% for item in qss%}
            <a href="{{ url_for('qa.questions', question_id=item.id) }}">
            <article class="question single-question question-type-normal">
                <h2>{{ item.name }}</h2>
                <div class="question-type-main"><i class="icon-question-sign"></i>问题</div>
                <div class="question-inner">
                    {{ item.content }}
                </div>
            </article>
            </a>
            {% endfor %}
        </div>
        {% if current_user.is_authenticated %}
        <aside class="col-md-3 sidebar">
            <div class="widget">
                    <h3 class="widget_title">用户名：{{ current_user.username }}</h3>
                    <a href="{{url_for("auth.logout")}}">
                        <input type="button" value="退出登录" class="button color small">
                    </a>
            </div>
        </aside>
        {% endif %}
    </div>
</section>
{% endblock %}

{% block footer %}
<script src="/static/js/questionlist.js"></script>
{% endblock %}