python/20190311/my_djangos/django_community_app/community/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('authentication.urls')),
    path('', include('user_profile.urls')),
    path('', include('questions.urls')),
    path('', include('search.urls')),
    path('', include('oauth.urls')),
]

python/20190311/my_djangos/django_community_app/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

python/20190311/my_djangos/django_community_app/oauth/urls.py
from django.urls import path
from . import views

app_name = 'oauth'

urlpatterns = [
    path('oauth/github_login', views.git_login, name='github_login'),
    path('oauth/github_check', views.git_check, name='github_check'),
]

python/20190311/my_djangos/django_community_app/questions/urls.py
from django.urls import path
from .views import QuestionDetailView, QuestionListView, CreateQuestionView, create_answer

app_name = 'questions'

urlpatterns = [
    path('questions/', QuestionListView.as_view(), name='question_list'),
    path('questions/add/', CreateQuestionView.as_view(), name='question_add'),
    path('questions/<int:pk>/', QuestionDetailView.as_view(), name='question_detail'),
    path('questions/<int:pk>/add', create_answer, name='answer_add'),
]

python/20190311/my_djangos/django_community_app/search/urls.py
from django.urls import path, include
from .views import search

app_name = 'search'

urlpatterns = [
    path('search/', search, name='search'),
]

python/20190311/my_djangos/django_community_app/user_profile/urls.py
from django.urls import path
from .views import ProfileDetailView, UpdateProfileView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'user_profile'

urlpatterns = [
    path('user/<int:user_id>/', ProfileDetailView.as_view(), name='profile'),
    path('user/<int:user_id>/edit', UpdateProfileView.as_view(), name='update_profile'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/20190311/my_djangos/django_community_app/templates/base.html
{% load i18n %}
{% load staticfiles %}
<html lang="{% get_current_language as LANGUAGE_CODE %}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Community{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/bootcamp.css' %}" rel="stylesheet">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block head %}
    {% endblock head %}
</head>
<body>
{% block body %}
    <header>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">Community</a>
                </div>
                <div class="collapse navbar-collapse" id="menu">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'questions:question_list' %}">{% trans 'Q&A' %}</a></li>
                    </ul>

                    {% if not hide_search %}
                        <form class="navbar-form navbar-left" role="search" action="{% url 'search:search' %}">
                            <div class="input-group" style="width:210px">
                                <input type="text" class="form-control" name="q" placeholder="{% trans 'Search' %}">
                    <span class="input-group-btn">
                      <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span>
                      </button>
                    </span>
                            </div>
                        </form>
                    {% endif %}

                    <ul class="nav navbar-nav navbar-right">
                        {% if not user.is_anonymous %}
                            <li><a href="#">{{ user.get_username }}</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'user_profile:profile' user.id %}">{% trans 'profile' %}</a></li>
                                    <li class="divider"></li>
                                    <li><a href="{% url 'authentication:logout' %}">{% trans 'Log out' %}</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{% url 'authentication:signup' %}">{% trans 'Sign up' %}</a></li>
                            <li><a href="{% url 'authentication:login' %}">{% trans 'Log in' %}</a></li>
                            <li></li>
                            <li>
                                <div id="oauth_button">
                                    <div class="pull-right">
                                        <a href="{% url 'oauth:github_login' %}"><img width="15px" height="15px" class="type" src="{% static 'img/github.png' %}" alt="GITHUB"/></a>&nbsp;
                                        <a href="#"><img width="15px" height="15px" class="type" src="{% static 'img/QQ.png' %}" alt="QQ"/></a>&nbsp;
                                        <a href="#"><img width="15px" height="15px" class="type" src="{% static 'img/weibo.png' %}" alt="WEIBO"/></a>
                                    </div>
                                </div>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            {% block main %}
            {% endblock main %}
        </div>
    </main>
{% endblock body %}
<script src="{% static 'js/ga.js' %}"></script>
</body>
</html>