python/20190311/my_djangos/django_allwork_app/allwork/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('', include('users.urls')),
    path('', include('jobs.urls')),
    path('', include('chats.urls')),
]

python/20190311/my_djangos/django_allwork_app/chats/urls.py
from django.urls import path, include
from .views import (MessageView, MessageDetailView)

app_name = 'chats'

urlpatterns = [
    # 认证路由
    path('chats/', include([
        path('', MessageView.as_view(), name='list_message'),
        path('<int:pk>/', MessageDetailView.as_view(), name='user_message'),
    ])),
]

python/20190311/my_djangos/django_allwork_app/jobs/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from .views import (
    JobListView, JobCreateView, JobApplyView, ProposalAcceptView, JobDetailView, JobCloseView
)

app_name = 'jobs'

urlpatterns = [
    # 认证路由
    path('jobs/', include([
        path('', JobListView.as_view(), name='job_list'),
        path('add/', JobCreateView.as_view(), name='job_add'),
        path('<int:pk>/', JobDetailView.as_view(), name='job_detail'),
        path('<int:pk>/apply', JobApplyView.as_view(), name='job_apply'),
        path('<int:pk>/accept/<str:username>', ProposalAcceptView.as_view(), name='proposal_accept'),
        path('<int:pk>/close', JobCloseView.as_view(), name='job_close'),
    ])),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/20190311/my_djangos/django_allwork_app/users/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_view
from .views import (
    SignUpView, UserDetailView, UpdateProfileView,
    FreelancerSignUpView, ListFreelancersView, UserJobProfileView,
    OwnerSignUpView)

app_name = 'users'

urlpatterns = [
    # 认证路由
    path('accounts/', include([
        path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
        path('logout/', auth_view.LogoutView.as_view(), name='logout'),
        path('signup/', SignUpView.as_view(), name='signup'),
        path('signup/freelancer/', FreelancerSignUpView.as_view(), name='freelancer_signup'),
        path('signup/owner/', OwnerSignUpView.as_view(), name='owner_signup'),
    ])),
    # 自由竞争者列表路由
    path('freelancers/', ListFreelancersView.as_view(), name='list_freelancer'),
    # 个人信息路由
    path('user/', include([
        path('<int:pk>/edit', UpdateProfileView.as_view(), name='update_profile'),
        path('<str:username>/', UserDetailView.as_view(), name='user_profile'),
        path('<str:username>/jobs/', UserJobProfileView.as_view(), name='job_profile'),
    ])),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/20190311/my_djangos/django_allwork_app/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Allwork{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontello.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}" />
    {% if user.is_authenticated and user.is_owner %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/owners.css' %}">
    {% else %}
      <!--<link rel="stylesheet" type="text/css" href="{% static 'css/freelancers.css' %}">-->
    {% endif %}
    {% block styles %}

    {% endblock %}
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'home' %}" >Allwork</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            {% if user.is_authenticated %}
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link btn btn-sm btn-outline-secondary float-right" href="{% url 'users:job_profile' user.username %}" >My jobs </a>
                        </li>
                        <li>
                            <a  href="{% url 'chats:list_message'  %}" class=" nav-link  btn btn-sm btn-outline-secondary float-right" type="button">Messages</a>
                        </li>
                        <li>
                            <a  href="{% url 'jobs:job_list' %}" class=" nav-link  btn btn-sm btn-outline-secondary float-right" type="button">All jobs</a>
                        </li>
                    </ul>
                </div>

            {% else %}
                <a href="{% url 'users:login' %}" class="btn btn-outline-success" role="button">Log in</a>
                <a href="{% url 'users:signup' %}" class="btn btn-outline-success" role="button">Sign up</a>
            {% endif %}


            {% if user.is_authenticated and user.is_owner %}
            <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
                <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{% url 'jobs:job_add' %}" class="nav-link  btn btn-sm btn-outline-secondary float-right" type="button">Create Job</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'users:list_freelancer' %}" class="nav-link  btn btn-sm btn-outline-secondary float-right" type="button">Freelancers</a>
                        </li>
                </ul>
            </div>
            {% endif %}

            {% if user.is_authenticated %}
                <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle btn btn-sm btn-outline-secondary float-right" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'users:user_profile' user.username  %}">Settings</a>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                        </div>
                        </li>
                    </ul>
                </div>
            {% endif %}

        </nav>
    </div>

    <div class="container my-4">
        <div class="row justify-content-center">
            <div class="col-md-10 col-sm-12">
                <div class="card mb-3">
                    <div class="card-body">
                        {% block content %}

                        {% endblock %}
                    </div >
                </div>
                <footer>
                    We are here to serve you better!
                </footer>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
</body>
</html>

python/20190311/my_djangos/django_allwork_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <h2>Welcome to the Allwork!</h2>
    <p class="lead">
        If you already have an account, go ahead and <a href="{% url 'users:login' %}">log in</a>. If you are new to Allworks, get started
        by creating a <a href="{% url 'users:freelancer_signup' %}">Freelancer account</a> or a <a href="{% url 'users:owner_signup'%}">Project owner account</a>.
    </p>
    <hr>
    <h3>What's this about?</h3>
    <p>
        Creating job marketplace...
    </p>

{% endblock %}